version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app
permissions:
  - object: /home/ubuntu/app
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStop:
  - location: /home/ubuntu/app/codedeploy/applicationStop.sh
    timeout: 100
    runas: ubuntu

  ApllicationStart:
  - location: /home/ubuntu/app/codedeploy/applicationStart.sh
    timeout: 100
    runas: ubuntu
