version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app

hooks:
  ApplicationStop:
  - location: codedeploy/applicationStop.sh
    timeout: 100
    runas: ubuntu

  ApplicationStart:
  - location: codedeploy/applicationStart.sh
    timeout: 100
    runas: ubuntu
